version: "3.8"
services:
  database:
    container_name: mysql80
    build:
      context: .
      dockerfile: ./.docker/mysql/Dockerfile
    ports:
      - 13306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: webagre
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci --skip-character-set-client-handshake
    volumes:
      - mysql-db:/var/lib/mysql
    networks:
      internal:
        aliases:
          - database-local

  web:
    container_name: php81_web
    build:
      context: .
      dockerfile: ./.docker/php/Dockerfile
    ports:
      - 80:80
      - 443:443
    volumes:
      - .:/var/www/html
      - .docker/php/files/zend_debugger.ini:/etc/php.d/zend_debugger.ini
    depends_on:
      - database
    networks:
      internal:

  php-composer:
    build:
      context: ./.docker/composer
    volumes:
      - .:/app
    command: composer install --ignore-platform-reqs --no-scripts

  selenium:
    shm_size: '2gb'
    image: selenium/standalone-chrome-debug
    ports:
      - 4444:4444
      - 5900:5900
    depends_on:
      - web
    privileged: true

networks:
  internal:
    external:
      name: network-internal

volumes:
  mysql-db:
